import React, { useEffect, useState } from 'react'
import Card from '../components/Card'
import FormField from '../components/FormField'
import Loader from "../components/Loader"

const Home = () => {

  
  const [ loading, setLoading] = useState(true)
  const [ allPosts, setAllPosts] = useState([])
  return (
    <section className=' max-w-7xl'>
      <div>
        <h1 className=' text-[#222328] text-[32px] font-extrabold'>
          The Community Showcase
        </h1>
        <p className=' mt-2 text-[#66e75] text-[14px]  max-w-[500px]  '>Browse through a collection of imaginative and visually appealing images generated by DALL-E AI</p>
      </div>
      <div className=' mt-16'>
        <FormField/>
        
      </div>
      <div className=' mt-10'>
        {loading ? ( <div>
          <Loader/>
        </div>) : (
          <></>
        )}

      </div>

    </section>
  )
}

export default Home